SELECT BUSINESS_ID
FROM(
    SELECT BUSINESS_ID FROM EVENTS A
    JOIN(
        SELECT EVENT_TYPE, AVG(OCCURENCES) AS AVG 
        FROM EVENTS
        GROUP BY EVENT_TYPE) B
    ON A.EVENT_TYPE = B.EVENT_TYPE
    AND A.OCCURENCES > B.AVG) C    
GROUP BY BUSINESS_ID
HAVING COUNT(*) > 1
