CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
    DECLARE N_SALARY INT DEFAULT NULL;
    DECLARE M INT;
    SET M = N-1;
    SELECT DISTINCT(SALARY) INTO N_SALARY 
    FROM EMPLOYEE
    ORDER BY SALARY DESC
    LIMIT 1 OFFSET M;
    RETURN N_SALARY;
END;
