SELECT A.PROJECT_ID, A.EMPLOYEE_ID
FROM
(SELECT PROJECT_ID, E.EMPLOYEE_ID, EXPERIENCE_YEARS
FROM PROJECT P 
LEFT JOIN EMPLOYEE E
ON P.EMPLOYEE_ID = E.EMPLOYEE_ID) A,
(SELECT PROJECT_ID, E.EMPLOYEE_ID, MAX(EXPERIENCE_YEARS) AS YEARS
FROM PROJECT P
LEFT JOIN EMPLOYEE E
ON P.EMPLOYEE_ID = E.EMPLOYEE_ID
GROUP BY PROJECT_ID) B
WHERE A.PROJECT_ID = B.PROJECT_ID
AND A.EXPERIENCE_YEARS = B.YEARS
