SELECT DISTINCT(BUYER_ID) FROM SALES
WHERE BUYER_ID IN (
    SELECT S.BUYER_ID FROM SALES S
    INNER JOIN PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.PRODUCT_NAME = 'S8')
AND BUYER_ID NOT IN (
    SELECT S.BUYER_ID FROM SALES S
    INNER JOIN PRODUCT P
    ON S.PRODUCT_ID = P.PRODUCT_ID
    WHERE P.PRODUCT_NAME = 'iPhone')
